CREATE OR REPLACE FUNCTION getp72rissmktissoid(p_bbunique Varchar DEFAULT NULL,p_bbcptickid Varchar DEFAULT NULL, p_bbcmpsecid varchar DEFAULT NULL, p_bbglobalid varchar DEFAULT NULL, p_cpglobalid varchar DEFAULT NULL, p_ricid varchar DEFAULT NULL)
RETURNS VARCHAR
 LANGUAGE plpgsql
AS $function$
DECLARE
V_OUTPUT VARCHAR(254):= NULL;
BEGIN

if p_bbunique  IS NOT NULL and p_bbunique !=''  then
	SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
    FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
	WHERE ISID.ISID_OID=MIXR.ISID_OID 
	AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
	AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
	AND ISID.ID_CTXT_TYP='BBUNIQUE'
	AND MKIS.ofcl_place_listing_ind ='Y'
	AND ISID.ISS_ID=p_bbunique;
if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;

if p_bbcptickID  IS NOT NULL and p_bbcptickID !=''  then
	SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
    FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
	WHERE ISID.ISID_OID=MIXR.ISID_OID 
	AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
	AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
	AND ISID.ID_CTXT_TYP='BBCPTICK'
	AND MKIS.ofcl_place_listing_ind ='Y'
	AND ISID.ISS_ID=p_bbcptickID;
if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;	
if p_bbcmpsecID is not null and p_bbcmpsecID!='' then
	SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
	FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
	WHERE ISID.ISID_OID=MIXR.ISID_OID 
	AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
	AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
	AND ISID.ID_CTXT_TYP='BBCMPSEC'
	AND MKIS.ofcl_place_listing_ind ='Y'
	AND ISID.ISS_ID=p_bbcmpsecID ;
 if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;

if p_bbglobalID is not null or p_bbglobalID !='' then
	SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
	FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
	WHERE ISID.ISID_OID=MIXR.ISID_OID 
    AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
	AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
	AND ISID.ID_CTXT_TYP='BBGLOBAL'
	AND MKIS.ofcl_place_listing_ind ='Y'
	AND ISID.ISS_ID=p_bbglobalID;
 if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;

if p_cpglobalID is not null or p_cpglobalID!='' then
  SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
  FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
  WHERE ISID.ISID_OID=MIXR.ISID_OID 
  AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
  AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
  AND ISID.ID_CTXT_TYP='CPGLOBAL'
AND MKIS.ofcl_place_listing_ind ='Y'
  AND ISID.ISS_ID=p_cpglobalID ;
 
 if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;	

if p_ricID is not null or p_ricID !='' then
	SELECT MKIS.MKT_ISS_OID||'|'||ISID.ID_CTXT_TYP into V_OUTPUT
	FROM FT_T_ISID ISID, FT_T_MIXR MIXR, FT_T_MKIS MKIS 
	WHERE ISID.ISID_OID=MIXR.ISID_OID 
    AND MIXR.MKT_ISS_OID=MKIS.MKT_ISS_OID 
	AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE()) 
	AND ISID.ID_CTXT_TYP='RIC'
	AND MKIS.ofcl_place_listing_ind ='Y'
	AND ISID.ISS_ID=p_ricID;
 if V_OUTPUT  IS NOT NULL and V_OUTPUT !=''  then
	RETURN V_OUTPUT;
END IF ;
end if;

 RETURN V_OUTPUT;

END;
$function$
;
