CREATE OR REPLACE FUNCTION GETP72PANOSECTYPASGN(P_INSTRID VARCHAR DEFAULT NULL)
RETURNS VARCHAR
LANGUAGE PLPGSQL
AS $FUNCTION$
DECLARE
V_OUTPUT VARCHAR(254):= NULL;
V_LEVEL1 VARCHAR(254):= NULL;
V_LEVEL2 VARCHAR(254):= NULL;
V_INDSUBGROUP VARCHAR(254):= NULL;
BEGIN
	

	
    IF P_INSTRID IS NOT NULL THEN
	
	
		select GETP72INSTRTYPE(P_INSTRID,'1') INTO V_LEVEL1 from DUAL;
		
		select GETP72INSTRTYPE(P_INSTRID,'2') INTO V_LEVEL2 from DUAL;
		

		IF V_LEVEL1 IS NOT NULL OR V_LEVEL2 IS NOT NULL THEN
		
				BEGIN
				
					SELECT ISCL.CL_VALUE INTO V_INDSUBGROUP
						FROM FT_T_ISCL ISCL
						WHERE ISCL.INSTR_ID=P_INSTRID
						AND ISCL.INDUS_CL_SET_ID='BBINDSGR'
						AND (ISCL.END_TMS IS NULL OR ISCL.END_TMS > SYSDATE());
				EXCEPTION
					WHEN NO_DATA_FOUND THEN V_INDSUBGROUP := NULL;
				END;
						
				IF (V_LEVEL1 IN ('Equity','Funds') OR V_LEVEL2 IN ('Equity Rights', 'Equity Warrants')) 
						AND V_INDSUBGROUP = 'Specified Purpose Acquis' THEN
				
				V_OUTPUT := 'SPAC';	
				
				ELSE
				
					BEGIN
				
						SELECT ISCL.CL_VALUE INTO V_OUTPUT
							FROM FT_T_ISCL ISCL
							WHERE ISCL.INSTR_ID=P_INSTRID
							AND ISCL.INDUS_CL_SET_ID='BBSECTYP'
							AND ISCL.CLSF_PURP_TYP='BBISSTYP'
							AND (ISCL.END_TMS IS NULL OR ISCL.END_TMS > SYSDATE())
							LIMIT 1;
							
					EXCEPTION
					WHEN NO_DATA_FOUND THEN V_OUTPUT := NULL;
					END;	
				
				END IF;
		
		
		END IF;
		
    END IF;


RETURN V_OUTPUT;

END;
$FUNCTION$
;
