CREATE or REPLACE VIEW FT_V_P72_BARRA
AS 
SELECT  BARRA_ID, COALESCE(BARRA_ID,'') || '|' ||
COALESCE(SEDOL ,'')|| '|' ||
COALESCE(CINS,'') || '|' ||
COALESCE(CUSIP,'') || '|' ||
COALESCE(ISIN,'') || '|' ||
(SELECT START_DATE FROM FT_T_BAR1 WHERE BARRA_ID=ABC.BARRA_ID  AND START_DATE IS NOT NULL LIMIT 1) || '|' ||
(SELECT END_DATE FROM FT_T_BAR1 WHERE BARRA_ID=ABC.BARRA_ID  AND END_DATE IS NOT NULL LIMIT 1) AS OP
FROM (
SELECT BARRA_ID,
MAX(CASE WHEN (ASSET_ID_TYPE='SEDOL') THEN ASSET_ID ELSE NULL END) AS SEDOL,
MAX(CASE WHEN (ASSET_ID_TYPE='CINS') THEN ASSET_ID ELSE NULL END) AS CINS,
MAX(CASE WHEN (ASSET_ID_TYPE='CUSIP') THEN ASSET_ID ELSE NULL END) AS CUSIP,
MAX(CASE WHEN (ASSET_ID_TYPE='ISIN') THEN ASSET_ID ELSE NULL END) AS ISIN
FROM FT_T_BAR1
GROUP BY BARRA_ID
ORDER BY BARRA_ID) ABC