CREATE OR REPLACE FUNCTION getp72icsmapping(p_instrid varchar DEFAULT NULL, p_countryiso varchar DEFAULT NULL, p_mktissoid varchar DEFAULT NULL)
 RETURNS VARCHAR
 LANGUAGE plpgsql
AS $function$
declare
P_INSTRID VARCHAR(254):=P_INSTRID;
V_OUTPUT VARCHAR(254):= NULL;
V_LEVEL1 VARCHAR(254):= NULL;
V_LEVEL2 VARCHAR(254):= NULL;
P_COUNTRYISO VARCHAR(254):= P_COUNTRYISO;
P_MKTISSOID VARCHAR(254):= p_mktissoid;
BEGIN


IF P_INSTRID IS NOT NULL AND P_COUNTRYISO IS NOT NULL AND P_MKTISSOID IS NOT NULL THEN


select GETP72INSTRTYPE(P_INSTRID,'1') INTO V_LEVEL1 from DUAL;

select GETP72INSTRTYPE(P_INSTRID,'2') INTO V_LEVEL2 from DUAL;


IF V_LEVEL1 IS NOT null OR V_LEVEL2 IS NOT null THEN

	IF V_LEVEL1 = 'Equity' AND V_LEVEL2 ='Preference' AND P_COUNTRYISO = 'US' THEN
		SELECT ISID.ISS_ID  INTO V_OUTPUT
				FROM FT_T_ISID ISID, FT_T_MIXR MIXR
				WHERE ISID.ISID_OID=MIXR.ISID_OID
				AND ISID.ID_CTXT_TYP='TICKER'
				AND MIXR.MKT_ISS_OID=P_MKTISSOID
				AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE())
				AND (MIXR.END_TMS IS NULL OR MIXR.END_TMS > SYSDATE());
	
	ELSIF V_LEVEL1 = 'Equity' AND V_LEVEL2 IN ('Preferred Stock','Convertible Preferred Stock',
											   'Depository Receipts','Preference', 
											   'Preferred Stock','Convertible Preferred Stock') THEN
		SELECT ISID.ISS_ID INTO V_OUTPUT
				FROM FT_T_ISID ISID, FT_T_MIXR MIXR
				WHERE ISID.ISID_OID=MIXR.ISID_OID
				AND ISID.ID_CTXT_TYP='TICKER'
				AND MIXR.MKT_ISS_OID=P_MKTISSOID
				AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE())
				AND (MIXR.END_TMS IS NULL OR MIXR.END_TMS > SYSDATE());
		
	ELSIF V_LEVEL1 = 'Equity'  AND P_COUNTRYISO != 'US' THEN
		SELECT ISID.ISS_ID INTO V_OUTPUT
				FROM FT_T_ISID ISID, FT_T_MIXR MIXR
				WHERE ISID.ISID_OID=MIXR.ISID_OID
				AND ISID.ID_CTXT_TYP='RIC'
				AND MIXR.MKT_ISS_OID=P_MKTISSOID
				AND PRIM_TRD_MRKT_QUOTE_IND = 'Y'
				AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE())
				AND (MIXR.END_TMS IS NULL OR MIXR.END_TMS > SYSDATE());
				
		IF V_OUTPUT IS NULL THEN
		SELECT ISID.ISS_ID INTO V_OUTPUT
				FROM FT_T_ISID ISID, FT_T_MIXR MIXR
				WHERE ISID.ISID_OID=MIXR.ISID_OID
				AND ISID.ID_CTXT_TYP='RIC'
				AND MIXR.MKT_ISS_OID=P_MKTISSOID				
				AND (ISID.END_TMS IS NULL OR ISID.END_TMS > SYSDATE())
				AND (MIXR.END_TMS IS NULL OR MIXR.END_TMS > SYSDATE());
		END IF;
		
	END IF;

END IF;

END IF;

RETURN V_OUTPUT;
end;
$function$
;
