DO $$
DECLARE
    v_ISSU_CHAL TEXT;
BEGIN
    v_ISSU_CHAL := '<?xml version="1.0" encoding="UTF-8" standalone="no"?><changeApprovalEntity><occurrence id="ISSU_01" table="FT_T_ISSU"><changeApprovalFields/></occurrence><occurrence id="ISID_CUSIP" parentId="ISSU_01" table="FT_T_ISID"><changeApprovalFields><field approval="SINGLE" label="InstrumentLevelIdentifiers.CUSIP" name="FT_T_ISID.ISS_ID"/></changeApprovalFields><where><field isNull="true" name="FT_T_ISID.MKT_OID"/><field name="FT_T_ISID.ID_CTXT_TYP"><value>CUSIP</value></field></where></occurrence><occurrence id="MKIS_PRIMARY" parentId="ISSU_01" table="FT_T_MKIS"><changeApprovalFields/></occurrence><occurrence id="MIXR_PRIMARY_BBTRDGSYMB" parentId="MKIS_PRIMARY" table="FT_T_MIXR"><changeApprovalFields/></occurrence><occurrence id="ISID_PRIMARY_BBTRDGSYMB" parentId="ISSU_01" table="FT_T_ISID"><changeApprovalFields><field approval="SINGLE" label="PrimaryMarket.PrimaryMarketBBTradingSymbol" name="FT_T_ISID.ISS_ID"/></changeApprovalFields><where><field isNull="false" name="FT_T_ISID.MKT_OID"/><field name="FT_T_ISID.ID_CTXT_TYP"><value>BBTRDGSYMB</value></field></where></occurrence><occurrence id="MIXR_PRIMARY_SEDOL" parentId="MKIS_PRIMARY" table="FT_T_MIXR"><changeApprovalFields/></occurrence><occurrence id="ISID_PRIMARY_SEDOL" parentId="ISSU_01" table="FT_T_ISID"><changeApprovalFields><field approval="SINGLE" label="PrimaryMarket.PrimaryMarketSEDOL" name="FT_T_ISID.ISS_ID"/></changeApprovalFields><where><field isNull="false" name="FT_T_ISID.MKT_OID"/><field name="FT_T_ISID.ID_CTXT_TYP"><value>SEDOL</value></field></where></occurrence><occurrence id="MIXR_PRIMARY_RIC" parentId="MKIS_PRIMARY" table="FT_T_MIXR"><changeApprovalFields/></occurrence><occurrence id="ISID_PRIMARY_RIC" parentId="ISSU_01" table="FT_T_ISID"><changeApprovalFields><field approval="SINGLE" label="PrimaryMarket.PrimaryMarketRIC" name="FT_T_ISID.ISS_ID"/></changeApprovalFields><where><field isNull="false" name="FT_T_ISID.MKT_OID"/><field name="FT_T_ISID.ID_CTXT_TYP"><value>RIC</value></field></where></occurrence><occurrence id="ISID_ISIN" parentId="ISSU_01" table="FT_T_ISID"><changeApprovalFields><field approval="SINGLE" label="InstrumentLevelIdentifiers.ISIN" name="FT_T_ISID.ISS_ID"/></changeApprovalFields><where><field isNull="true" name="FT_T_ISID.MKT_OID"/><field name="FT_T_ISID.ID_CTXT_TYP"><value>ISIN</value></field></where></occurrence></changeApprovalEntity>';
    

	Insert into FT_T_XCFG(XCFG_OID, XML_CONFIG_MNEM, XML_CONFIG_DESC, XML_CONFIG_REFRESH_IND, START_TMS, LAST_CHG_TMS, LAST_CHG_USR_ID, XML_CONFIG_CLOB, BUS_ENTITY_NME)
			Values ('GSCHALEQTY', 'CHALISSU', 'CHAL Configurations', 'N', SYSDATE(),  SYSDATE(), 'GS:PSG:P72', v_ISSU_CHAL, 'Equity');
			
	
END; 
$$