-- BBUNQEXH
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001001',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','BBUNQEXH','BBUNQEXH','BBUNIQUE And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'BBUNQEXH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001002',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','BBUNQEXH','BBUNQEXH','BBUNIQUE And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'BBUNQEXH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001003',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','BBUNQEXH','BBUNQEXH','BBUNIQUE And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'BBUNQEXH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001004',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','BBUNQEXH','BBUNQEXH','BBUNIQUE And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'BBUNQEXH');

-- TICKEQPMSH
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001005',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','TICKEQPMSH','TICKEQPMSH','Ticker And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'TICKEQPMSH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001006',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','TICKEQPMSH','TICKEQPMSH','Ticker And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'TICKEQPMSH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001007',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','TICKEQPMSH','TICKEQPMSH','Ticker And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'TICKEQPMSH');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001008',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','TICKEQPMSH','TICKEQPMSH','Ticker And Equity Prime Exch Short','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'TICKEQPMSH');

-- P72 BLOOMBERG Ticker (P72BBGTICK)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001009',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','P72BBGTICK','P72 BLOOMBERG Ticker','P72 BLOOMBERG Ticker','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'P72BBGTICK');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001010',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','P72BBGTICK','P72 BLOOMBERG Ticker','P72 BLOOMBERG Ticker','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'P72BBGTICK');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001011',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','P72BBGTICK','P72 BLOOMBERG Ticker','P72 BLOOMBERG Ticker','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'P72BBGTICK');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001012',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','P72BBGTICK','P72 BLOOMBERG Ticker','P72 BLOOMBERG Ticker','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'P72BBGTICK');

-- GV Underlying (GVUNDLPOSID)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001013',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','GVUNDLPOSID','GV Underlying','GV Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'GVUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001014',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','GVUNDLPOSID','GV Underlying','GV Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'GVUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001015',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','GVUNDLPOSID','GV Underlying','GV Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'GVUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001016',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','GVUNDLPOSID','GV Underlying','GV Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'GVUNDLPOSID');

-- P72 Ultimate Underlying (ULTUNDLPOSID)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001017',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','ULTUNDLPOSID','P72 Ultimate Underlying','P72 Ultimate Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'ULTUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001018',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','ULTUNDLPOSID','P72 Ultimate Underlying','P72 Ultimate Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'ULTUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001019',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','ULTUNDLPOSID','P72 Ultimate Underlying','P72 Ultimate Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'ULTUNDLPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001020',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','ULTUNDLPOSID','P72 Ultimate Underlying','P72 Ultimate Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'ULTUNDLPOSID');

-- Pano Risk Underlying (PANORISKPOSID)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001021',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','PANORISKPOSID','Pano Risk Underlying','Pano Risk Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'PANORISKPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001022',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','PANORISKPOSID','Pano Risk Underlying','Pano Risk Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'PANORISKPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001023',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','PANORISKPOSID','Pano Risk Underlying','Pano Risk Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'PANORISKPOSID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001024',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','PANORISKPOSID','Pano Risk Underlying','Pano Risk Underlying','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'PANORISKPOSID');

-- ICS Mapping (ICSMAPPING)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001025',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','ICSMAPPING','ICS Mapping','ICS Mapping','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'ICSMAPPING');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001026',NULL,'00004450',SYSDATE(),'GS:PSG:P72','N','ICSMAPPING','ICS Mapping','ICS Mapping','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004450' AND intrnl_dmn_val_txt = 'ICSMAPPING');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001027',NULL,'01841284',SYSDATE(),'GS:PSG:P72','N','ICSMAPPING','ICS Mapping','ICS Mapping','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841284' AND intrnl_dmn_val_txt = 'ICSMAPPING');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001028',NULL,'01841742',SYSDATE(),'GS:PSG:P72','N','ICSMAPPING','ICS Mapping','ICS Mapping','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '01841742' AND intrnl_dmn_val_txt = 'ICSMAPPING');

-- Sacramento Tech Exchange (SAC)
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001029',NULL,'00101581',SYSDATE(),'GS:PSG:P72','N','SAC','Sacramento Tech Exchange','Sacramento Tech Exchange','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00101581' AND intrnl_dmn_val_txt = 'SAC');

--CAPCOID
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001030',NULL,'00164025',SYSDATE(),'GS:PSG:P72','N','CAPCOID','CAPCO Identifier','CAPCO Identifier','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00164025' AND intrnl_dmn_val_txt = 'CAPCOID');

--CNTRPRIMID
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001031',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','CNTRPRIMID','Country Primary Id','Country Primary Id','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'CNTRPRIMID');

--GSPOSITIONID
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV001032',NULL,'00002875',SYSDATE(),'GS:PSG:P72','N','GSPOSITIONID','GS Position Id','GS Position Id','ACTIVE','P72',NULL, NULL     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00002875' AND intrnl_dmn_val_txt = 'GSPOSITIONID');

INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV000001',NULL,'00004180',current_date,'GS:PSG:P72','N','POSNSOI','Position SOI','Position SOI','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00004180' AND intrnl_dmn_val_txt = 'POSNSOI');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme)  SELECT 'IDMV000002','DSRCID',NULL,current_date,'GS:PSG:P72','N','P72','Point 72','Point 72','ACTIVE','P72','',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_data_cl_id = 'DSRCID' AND intrnl_dmn_val_txt = 'P72');

-- IACM.CMNT_REAS_TYP
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72SECID','P72 Security Identifier','P72 Security Identifier','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72SECID');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72SECIDTYPE','P72 Security Identifier Type','P72 Security Identifier Type','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72SECIDTYPE');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72CURRENCY','P72 Currency','P72 Currency','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72CURRENCY');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72COMPANYNAME','P72 Company Name','P72 Company Name','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72COMPANYNAME');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72BBGLOBAL','P72 Bloomberg Global ID','P72 Bloomberg Global ID','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72BBGLOBAL');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72BBUNIQUE','P72 Bloomberg Unique ID','P72 Bloomberg Unique ID','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72BBUNIQUE');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72SECTYP','P72 Bloomberg List Sec Type','P72 Bloomberg List Sec Type','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72SECTYP');
INSERT INTO ft_t_idmv (intrnl_dmn_val_id, fld_data_cl_id, fld_id, last_chg_tms, last_chg_usr_id, mod_rst_ind, intrnl_dmn_val_txt, intrnl_dmn_val_nme, intrnl_dmn_desc, data_stat_typ, data_src_id,tbl_id,col_nme, dmn_val_purp_typ ,qual_val_txt)  SELECT new_oid(),NULL,'00100029',SYSDATE(),'P72:CSTM','N','P72FEEDSOURCE','P72 Bloomberg Feed Source','P72 Bloomberg Feed Source','ACTIVE','P72','IACM', 'CMNT_REAS_TYP', NULL, NULL    FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_idmv WHERE fld_id = '00100029' AND intrnl_dmn_val_txt = 'P72FEEDSOURCE');



INSERT INTO ft_t_idmv (intrnl_dmn_val_id,fld_data_cl_id,fld_id,appl_id,last_chg_tms,last_chg_usr_id,mod_rst_ind,intrnl_dmn_val_nme,intrnl_dmn_val_txt,intrnl_dmn_desc,tbl_id,col_nme,ds_id,qual_fld_id,qual_val_txt,dmn_set_id,meta_src_id,data_stat_typ,org_id,dmn_val_purp_typ,data_src_id) VALUES
       (new_oid(),NULL,'01820173',NULL,sysdate(),'P72','S','Yes','Y','Yes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'GS');

INSERT INTO ft_t_idmv (intrnl_dmn_val_id,fld_data_cl_id,fld_id,appl_id,last_chg_tms,last_chg_usr_id,mod_rst_ind,intrnl_dmn_val_nme,intrnl_dmn_val_txt,intrnl_dmn_desc,tbl_id,col_nme,ds_id,qual_fld_id,qual_val_txt,dmn_set_id,meta_src_id,data_stat_typ,org_id,dmn_val_purp_typ,data_src_id) VALUES
       (new_oid(),NULL,'01820173',NULL,sysdate(),'P72','S','No','N','No',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'GS');

INSERT INTO ft_t_idmv (intrnl_dmn_val_id,fld_data_cl_id,fld_id,appl_id,last_chg_tms,last_chg_usr_id,mod_rst_ind,intrnl_dmn_val_nme,intrnl_dmn_val_txt,intrnl_dmn_desc,tbl_id,col_nme,ds_id,qual_fld_id,qual_val_txt,dmn_set_id,meta_src_id,data_stat_typ,org_id,dmn_val_purp_typ,data_src_id) VALUES
       (new_oid(),NULL,'01820173',NULL,sysdate(),'P72','S','Unknown','X','Unknown',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'GS');

