INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG185','SPAC Warrants','INSTYPGR','INSTYPGR05','Equity Warrants',3,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Warrants','SPAC Warrants',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Warrants' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 3);
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG186','SPAC Common Stock','INSTYPGR','INSTYPGR06','Common Stock',3,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Common Stock','SPAC Common Stock',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Common Stock' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 3);
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG187','SPAC Unit','INSTYPGR','INSTYPGR06','Common Stock',3,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Unit','SPAC Unit',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Unit' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 3);
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG188','SPAC Warrants','INSTYPGR','INSTYPG185','SPAC Warrants',4,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Warrants','SPAC Warrants',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Warrants' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 4);
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG189','SPAC Common Stock','INSTYPGR','INSTYPG186','SPAC Common Stock',4,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Common Stock','SPAC Common Stock',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Common Stock' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 4);
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, prnt_clsf_oid, prnt_cl_value, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'INSTYPG190','SPAC Unit','INSTYPGR','INSTYPG187','SPAC Unit',4,SYSDATE(),SYSDATE(),'GS:PSG:P72','SPAC Unit','SPAC Unit',''     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'SPAC Unit' AND indus_cl_set_id = 'INSTYPGR'  AND level_num = 4);

INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT 'EINC000778','INSTYPG188','SPAC Warrants','Specified Purpose Acquis-Warrants','INSTYPGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Specified Purpose Acquis','Specified Purpose Acquis','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'INSTYPG188' AND ext_cl_value = 'Specified Purpose Acquis-Warrants' AND indus_cl_set_id = 'INSTYPGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT 'EINC000779','INSTYPG189','SPAC Common Stock','Specified Purpose Acquis-Common Stock','INSTYPGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Specified Purpose Acquis','Specified Purpose Acquis','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'INSTYPG189' AND ext_cl_value = 'Specified Purpose Acquis-Common Stock' AND indus_cl_set_id = 'INSTYPGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT 'EINC000780','INSTYPG190','SPAC Unit','Specified Purpose Acquis-Unit','INSTYPGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Specified Purpose Acquis','Specified Purpose Acquis','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'INSTYPG190' AND ext_cl_value = 'Specified Purpose Acquis-Unit' AND indus_cl_set_id = 'INSTYPGR' AND data_src_id = 'BB');
