INSERT INTO FT_T_NTDF (APPL_ID, PART_ID, NOTFCN_ID, DFLT_SEVERITY_CDE, LAST_CHG_USR_ID, LAST_CHG_TMS, RSOLUT_TYP, EXCP_TYP,TECHNICAL_EXCP_IND)
  SELECT 'TPS', 'TRANS', 60001, 40, 'GS:PSG:P72', SYSDATE(),'INVESTGT','DATA FAILURE','N' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_NTDF WHERE APPL_ID = 'TPS' AND PART_ID = 'TRANS' AND NOTFCN_ID = 60001);

INSERT INTO FT_T_NTRS (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, SUGGEST_LONG_TXT, SUGGEST_EXTND_TXT)
  SELECT 'TPS', 'TRANS', 60001, 'DEFAULT', 'ENGLISH', SYSDATE(), 'GS:PSG:P72', 'To avoid this warning correct the input data.', 'To avoid this warning correct the input data.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_NTRS WHERE APPL_ID = 'TPS' AND PART_ID = 'TRANS' AND NOTFCN_ID = 60001);

INSERT INTO FT_T_NTXT (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, NOTFCN_SHORT_TXT, NOTFCN_LONG_TXT, NOTFCN_EXTND_TXT)
  SELECT 'TPS', 'TRANS', 60001, 'DEFAULT', 'ENGLISH', SYSDATE(), 'GS:PSG:P72', 'Warning during dataload.', 'Additional information: /%MsgText%/', 'A warning occurred during dataload. Additional information: /%MsgText%/.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_NTXT WHERE APPL_ID = 'TPS' AND PART_ID = 'TRANS' AND NOTFCN_ID = 60001);

INSERT INTO FT_T_NTPM (appl_Id, part_Id, notfcn_id, parm_nme, element_id, ds_id, fld_id, last_chg_usr_id, last_chg_tms, parm_desc)
  SELECT 'TPS', 'TRANS', 60001, 'MsgText', NULL, NULL, NULL, 'GS:PSG:P72', SYSDATE(), 'Vendor' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_NTPM WHERE APPL_ID = 'TPS' AND PART_ID = 'TRANS' AND NOTFCN_ID = 60001 AND PARM_NME = 'MsgText');
