INSERT INTO FT_T_NTDF (APPL_ID, PART_ID, NOTFCN_ID, DFLT_SEVERITY_CDE, LAST_CHG_USR_ID, LAST_CHG_TMS, RSOLUT_TYP, EXCP_TYP)  
SELECT 'STRDATA', 'RULEPRC', 40001, 50, 'P72:CSTM', SYSDATE(),'INVESTGT','VALIDATION'
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntdf WHERE NOTFCN_ID = '40001');

  
INSERT INTO FT_T_NTRS (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, SUGGEST_LONG_TXT, SUGGEST_EXTND_TXT)  
SELECT 'STRDATA', 'RULEPRC', 40001, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Kindly re-check input data', 'Validation failure, Kindly re-check input data '
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntrs WHERE NOTFCN_ID = '40001');


INSERT INTO FT_T_NTXT (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, NOTFCN_SHORT_TXT, NOTFCN_LONG_TXT, NOTFCN_EXTND_TXT)  
SELECT 'STRDATA', 'RULEPRC', 40001, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Custom Raised Error', 'Validation failure, Kindly re-check submitted data.', 'Message has been rejected due to following reason: /%REJECTREAS%/'
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntxt WHERE NOTFCN_ID = '40001');


INSERT INTO FT_T_NTPM (APPL_ID, PART_ID, NOTFCN_ID, PARM_NME, ELEMENT_ID, DS_ID, FLD_ID, LAST_CHG_USR_ID, LAST_CHG_TMS, PARM_DESC)  
SELECT 'STRDATA', 'RULEPRC', 40001, 'REJECTREAS', NULL, NULL, NULL, 'P72:CSTM', SYSDATE(), 'Rejection Reason' 
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntpm WHERE NOTFCN_ID = '40001');

--40002
INSERT INTO FT_T_NTDF (APPL_ID, PART_ID, NOTFCN_ID, DFLT_SEVERITY_CDE, LAST_CHG_USR_ID, LAST_CHG_TMS, RSOLUT_TYP, EXCP_TYP)  
SELECT 'STRDATA', 'RULEPRC', 40002, 40, 'P72:CSTM', SYSDATE(),'INVESTGT','VALIDATION'
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntdf WHERE NOTFCN_ID = '40002');
  
INSERT INTO FT_T_NTRS (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, SUGGEST_LONG_TXT, SUGGEST_EXTND_TXT)  
SELECT 'STRDATA', 'RULEPRC', 40002, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Kindly re-check input data', 'Validation failure, Kindly re-check input data '
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntrs WHERE NOTFCN_ID = '40002');

INSERT INTO FT_T_NTXT (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, NOTFCN_SHORT_TXT, NOTFCN_LONG_TXT, NOTFCN_EXTND_TXT)
SELECT 'STRDATA', 'RULEPRC', 40002, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Custom Raised Error', 'Validation failure, Kindly re-check submitted data.', 'Message has been rejected due to following reason: /%REJECTREAS%/'
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntxt WHERE NOTFCN_ID = '40002');


INSERT INTO FT_T_NTPM (APPL_ID, PART_ID, NOTFCN_ID, PARM_NME, ELEMENT_ID, DS_ID, FLD_ID, LAST_CHG_USR_ID, LAST_CHG_TMS, PARM_DESC)
SELECT 'STRDATA', 'RULEPRC', 40002, 'REJECTREAS', NULL, NULL, NULL, 'P72:CSTM', SYSDATE(), 'Rejection Reason' 
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntpm WHERE NOTFCN_ID = '40002');


--40003
INSERT INTO FT_T_NTDF (APPL_ID, PART_ID, NOTFCN_ID, DFLT_SEVERITY_CDE, LAST_CHG_USR_ID, LAST_CHG_TMS, RSOLUT_TYP, EXCP_TYP)  
SELECT 'STRDATA', 'RULEPRC', 40003, 40, 'P72:CSTM', SYSDATE(),'INVESTGT','VALIDATION'
     FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntdf WHERE NOTFCN_ID = '40003');
  
INSERT INTO FT_T_NTRS (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, SUGGEST_LONG_TXT, SUGGEST_EXTND_TXT)  
SELECT 'STRDATA', 'RULEPRC', 40003, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Kindly check data for INSTR_ID or MKT_ISS_OID', 'Validation failure, INSTR_ID or MKT_ISS_OID was not found in table IADC'
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntrs WHERE NOTFCN_ID = '40003');

INSERT INTO FT_T_NTXT (APPL_ID, PART_ID, NOTFCN_ID, USR_CAT_TYP, NLS_CDE, LAST_CHG_TMS, LAST_CHG_USR_ID, NOTFCN_SHORT_TXT, NOTFCN_LONG_TXT, NOTFCN_EXTND_TXT)
SELECT 'STRDATA', 'RULEPRC', 40003, 'DEFAULT', 'ENGLISH', SYSDATE(), 'P72:CSTM', 'Custom Raised Error', 'INSTR_ID or MKT_ISS_OID was not found in table IADC', 'INSTR_ID or MKT_ISS_OID was not found in table IADC'
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntxt WHERE NOTFCN_ID = '40003');


INSERT INTO FT_T_NTPM (APPL_ID, PART_ID, NOTFCN_ID, PARM_NME, ELEMENT_ID, DS_ID, FLD_ID, LAST_CHG_USR_ID, LAST_CHG_TMS, PARM_DESC)
SELECT 'STRDATA', 'RULEPRC', 40003, 'REJECTREAS', NULL, NULL, NULL, 'P72:CSTM', SYSDATE(), 'Rejection Reason' 
	FROM DUAL WHERE NOT EXISTS (SELECT 'X' FROM ft_t_ntpm WHERE NOTFCN_ID = '40003');