INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR13','Agency Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt','Agency Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Agency Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR14','Agency Debt Tax Exempt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt Tax Exempt','Agency Debt Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Agency Debt Tax Exempt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR15','Corporate Inflation Linked','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Corporate Inflation Linked','Corporate Inflation Linked','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Corporate Inflation Linked' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR16','Foreign Convertible Bond','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Convertible Bond','Foreign Convertible Bond','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Convertible Bond' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR17','Foreign Corporate Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Corporate Debt','Foreign Corporate Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Corporate Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR18','Foreign Government Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Government Debt','Foreign Government Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Government Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR19','Foreign Inflation-Protected Securities','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Inflation-Protected Securities','Foreign Inflation-Protected Securities','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Inflation-Protected Securities' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR20','Foreign Municipal Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Municipal Debt','Foreign Municipal Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Municipal Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR21','Foreign Perpetual Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Perpetual Debt','Foreign Perpetual Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Perpetual Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR22','Foreign Structured Notes','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Structured Notes','Foreign Structured Notes','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Structured Notes' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR23','GSE Debt Non-Tax Exempt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Non-Tax Exempt','GSE Debt Non-Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'GSE Debt Non-Tax Exempt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR24','GSE Debt Tax Exempt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Tax Exempt','GSE Debt Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'GSE Debt Tax Exempt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR25','Supranational Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Supranational Debt','Supranational Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Supranational Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR26','Term Loan','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Term Loan','Term Loan','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Term Loan' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR27','US Convertible Bond','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Convertible Bond','US Convertible Bond','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Convertible Bond' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR28','US Corporate Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Corporate Debt','US Corporate Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Corporate Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR29','US Government Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Government Debt','US Government Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Government Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR30','US Municipal Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Municipal Debt','US Municipal Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Municipal Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR31','US Perpetual Debt','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Perpetual Debt','US Perpetual Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Perpetual Debt' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR32','US Structured Notes','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Structured Notes','US Structured Notes','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Structured Notes' AND indus_cl_set_id = 'GVPRNTGR');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVPRNTGR33','US Treasury Inflation-Protected Security (TIPS)','GVPRNTGR',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Treasury Inflation-Protected Security (TIPS)','US Treasury Inflation-Protected Security (TIPS)','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Treasury Inflation-Protected Security (TIPS)' AND indus_cl_set_id = 'GVPRNTGR');



