INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP20','Agency Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt','Agency Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Agency Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP21','Agency Debt Tax Exempt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt Tax Exempt','Agency Debt Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Agency Debt Tax Exempt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP22','Corporate Inflation Linked','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Corporate Inflation Linked','Corporate Inflation Linked','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Corporate Inflation Linked' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP23','Foreign Convertible Bond','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Convertible Bond','Foreign Convertible Bond','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Convertible Bond' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP24','Foreign Corporate Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Corporate Debt','Foreign Corporate Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Corporate Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP25','Foreign Government Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Government Debt','Foreign Government Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Government Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP26','Foreign Inflation-Protected Securities','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Inflation-Protected Securities','Foreign Inflation-Protected Securities','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Inflation-Protected Securities' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP27','Foreign Municipal Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Municipal Debt','Foreign Municipal Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Municipal Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP28','Foreign Perpetual Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Perpetual Debt','Foreign Perpetual Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Perpetual Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP29','Foreign Structured Notes','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Structured Notes','Foreign Structured Notes','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Foreign Structured Notes' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP30','GSE Debt Non-Tax Exempt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Non-Tax Exempt','GSE Debt Non-Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'GSE Debt Non-Tax Exempt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP31','GSE Debt Tax Exempt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Tax Exempt','GSE Debt Tax Exempt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'GSE Debt Tax Exempt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP32','Supranational Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Supranational Debt','Supranational Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Supranational Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP33','Term Loan','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','Term Loan','Term Loan','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'Term Loan' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP34','US Convertible Bond','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Convertible Bond','US Convertible Bond','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Convertible Bond' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP35','US Corporate Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Corporate Debt','US Corporate Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Corporate Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP36','US Government Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Government Debt','US Government Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Government Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP37','US Municipal Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Municipal Debt','US Municipal Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Municipal Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP38','US Perpetual Debt','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Perpetual Debt','US Perpetual Debt','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Perpetual Debt' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP39','US Structured Notes','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Structured Notes','US Structured Notes','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Structured Notes' AND indus_cl_set_id = 'GVINVTYP');
INSERT INTO ft_t_incl (clsf_oid, cl_value, indus_cl_set_id, level_num, start_tms, last_chg_tms, last_chg_usr_id, cl_nme, cl_desc,data_src_id)  SELECT 'GVINVTYP40','US Treasury Inflation-Protected Security (TIPS)','GVINVTYP',1,SYSDATE(),SYSDATE(),'GS:PSG:P72','US Treasury Inflation-Protected Security (TIPS)','US Treasury Inflation-Protected Security (TIPS)','BB'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_incl WHERE cl_value = 'US Treasury Inflation-Protected Security (TIPS)' AND indus_cl_set_id = 'GVINVTYP');


