INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR13','Agency Debt','G-ALL-ALL-NL-N-N-NOBLIG-NISSR-GA-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt','Agency Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR13' AND ext_cl_value = 'G-ALL-ALL-NL-N-N-NOBLIG-NISSR-GA-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR13','Agency Debt','C-ALL-ALL-NL-N-N-NOBLIG-NISSR-SP-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt','Agency Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR13' AND ext_cl_value = 'C-ALL-ALL-NL-N-N-NOBLIG-NISSR-SP-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR14','Agency Debt Tax Exempt','G-ALL-US-NL-N-N-OBLIG-NISSR-GA-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt Tax Exempt','Agency Debt Tax Exempt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR14' AND ext_cl_value = 'G-ALL-US-NL-N-N-OBLIG-NISSR-GA-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR14','Agency Debt Tax Exempt','C-ALL-US-NL-N-N-OBLIG-NISSR-SP-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Agency Debt Tax Exempt','Agency Debt Tax Exempt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR14' AND ext_cl_value = 'C-ALL-US-NL-N-N-OBLIG-NISSR-SP-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR15','Corporate Inflation Linked','C-ALL-ALL-NL-Y-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Corporate Inflation Linked','Corporate Inflation Linked','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR15' AND ext_cl_value = 'C-ALL-ALL-NL-Y-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR16','Foreign Convertible Bond','C-ALL-NUS-NL-N-Y-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Convertible Bond','Foreign Convertible Bond','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR16' AND ext_cl_value = 'C-ALL-NUS-NL-N-Y-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR16','Foreign Convertible Bond','G-ALL-NUS-NL-N-Y-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Convertible Bond','Foreign Convertible Bond','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR16' AND ext_cl_value = 'G-ALL-NUS-NL-N-Y-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR17','Foreign Corporate Debt','C-N-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Corporate Debt','Foreign Corporate Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR17' AND ext_cl_value = 'C-N-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR18','Foreign Government Debt','G-N-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Government Debt','Foreign Government Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR18' AND ext_cl_value = 'G-N-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR19','Foreign Inflation-Protected Securities','G-ALL-NUS-NL-Y-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Inflation-Protected Securities','Foreign Inflation-Protected Securities','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR19' AND ext_cl_value = 'G-ALL-NUS-NL-Y-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR20','Foreign Municipal Debt','M-ALL-NUS-NL-ALL-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Municipal Debt','Foreign Municipal Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR20' AND ext_cl_value = 'M-ALL-NUS-NL-ALL-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR21','Foreign Perpetual Debt','G-Y-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Perpetual Debt','Foreign Perpetual Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR21' AND ext_cl_value = 'G-Y-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR21','Foreign Perpetual Debt','C-Y-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Perpetual Debt','Foreign Perpetual Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR21' AND ext_cl_value = 'C-Y-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR22','Foreign Structured Notes','G-ALL-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-Y','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Structured Notes','Foreign Structured Notes','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR22' AND ext_cl_value = 'G-ALL-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-Y' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR22','Foreign Structured Notes','C-ALL-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-Y','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Structured Notes','Foreign Structured Notes','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR22' AND ext_cl_value = 'C-ALL-NUS-NL-N-N-ALL-NISSR-NGASPSNAT-Y' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR23','GSE Debt Non-Tax Exempt','G-ALL-US-NL-N-N-ALL-FM-GA-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Non-Tax Exempt','GSE Debt Non-Tax Exempt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR23' AND ext_cl_value = 'G-ALL-US-NL-N-N-ALL-FM-GA-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR24','GSE Debt Tax Exempt','G-ALL-US-NL-N-N-ALL-FB-GA-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','GSE Debt Tax Exempt','GSE Debt Tax Exempt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR24' AND ext_cl_value = 'G-ALL-US-NL-N-N-ALL-FB-GA-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR25','Supranational Debt','C-ALL-SNAT-NL-N-N-ALL-NISSR-SNAT-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Supranational Debt','Supranational Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR25' AND ext_cl_value = 'C-ALL-SNAT-NL-N-N-ALL-NISSR-SNAT-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR26','Term Loan','C-ALL-ALL-L-ALL-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Term Loan','Term Loan','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR26' AND ext_cl_value = 'C-ALL-ALL-L-ALL-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR27','US Convertible Bond','C-ALL-US-NL-N-Y-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Convertible Bond','US Convertible Bond','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR27' AND ext_cl_value = 'C-ALL-US-NL-N-Y-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR27','US Convertible Bond','G-ALL-US-NL-N-Y-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Convertible Bond','US Convertible Bond','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR27' AND ext_cl_value = 'G-ALL-US-NL-N-Y-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR28','US Corporate Debt','C-N-US-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Corporate Debt','US Corporate Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR28' AND ext_cl_value = 'C-N-US-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR29','US Government Debt','G-N-US-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Government Debt','US Government Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR29' AND ext_cl_value = 'G-N-US-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR30','US Municipal Debt','M-ALL-US-NL-ALL-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Municipal Debt','US Municipal Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR30' AND ext_cl_value = 'M-ALL-US-NL-ALL-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR31','US Perpetual Debt','G-Y-US-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Perpetual Debt','US Perpetual Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR31' AND ext_cl_value = 'G-Y-US-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR31','US Perpetual Debt','C-Y-US-NL-N-N-ALL-NISSR-NGASPSNAT-N','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Perpetual Debt','US Perpetual Debt','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR31' AND ext_cl_value = 'C-Y-US-NL-N-N-ALL-NISSR-NGASPSNAT-N' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR32','US Structured Notes','G-ALL-US-NL-N-N-ALL-NISSR-NGASPSNAT-Y','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Structured Notes','US Structured Notes','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR32' AND ext_cl_value = 'G-ALL-US-NL-N-N-ALL-NISSR-NGASPSNAT-Y' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR32','US Structured Notes','C-ALL-US-NL-N-N-ALL-NISSR-NGASPSNAT-Y','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Structured Notes','US Structured Notes','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR32' AND ext_cl_value = 'C-ALL-US-NL-N-N-ALL-NISSR-NGASPSNAT-Y' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR33','US Treasury Inflation-Protected Security (TIPS)','G-ALL-US-NL-Y-ALL-ALL-NISSR-ALL-ALL','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Treasury Inflation-Protected Security (TIPS)','US Treasury Inflation-Protected Security (TIPS)','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR33' AND ext_cl_value = 'G-ALL-US-NL-Y-ALL-ALL-NISSR-ALL-ALL' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');




INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR09','US Preferred Stock','P-US','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','US Preferred Stock','US Preferred Stock','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR09' AND ext_cl_value = 'P-US' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
INSERT INTO ft_t_einc (einc_oid, clsf_oid, cl_value, ext_cl_value, indus_cl_set_id, start_tms, last_chg_tms, last_chg_usr_id, ext_clsf_nme, ext_clsf_desc, data_src_id, nls_cde)  SELECT new_oid(),'GVPRNTGR02','Foreign Preferred Stock','P-NUS','GVPRNTGR',SYSDATE(),SYSDATE(),'GS:PSG:P72','Foreign Preferred Stock','Foreign Preferred Stock','BB','ENGLISH'     FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ft_t_einc WHERE clsf_oid = 'GVPRNTGR02' AND ext_cl_value = 'P-NUS' AND indus_cl_set_id = 'GVPRNTGR' AND data_src_id = 'BB');
